"""Season discovery, catalogs, build ledgers, and curated dataset layout."""

from nba_lineup_model.season.fetch import (
    RawArtifactEvidence,
    artifact_evidence,
    failed_fetch_record,
    fetch_game_raw,
    is_transient_fetch_error,
    select_catalog_games,
)
from nba_lineup_model.season.layout import (
    CURATED_TABLES,
    CuratedDatasetLayout,
    CuratedPartition,
)
from nba_lineup_model.season.schedule import (
    NbaScheduleClient,
    NbaScheduleError,
    ScheduleResponse,
    SeasonScheduleCache,
    catalog_from_schedule,
    replace_catalog_season,
)
from nba_lineup_model.season.schema import (
    BuildLedger,
    CatalogGame,
    FetchManifest,
    GameBuildRecord,
    GameCatalog,
    GameFetchRecord,
)
from nba_lineup_model.season.storage import (
    append_build_record,
    append_fetch_records,
    build_ledger_frame,
    build_ledger_from_frame,
    catalog_frame,
    catalog_from_frame,
    fetch_manifest_frame,
    fetch_manifest_from_frame,
    read_build_ledger,
    read_fetch_manifest,
    read_game_catalog,
    write_build_ledger,
    write_fetch_manifest,
    write_game_catalog,
)

__all__ = [
    "CURATED_TABLES",
    "BuildLedger",
    "CatalogGame",
    "CuratedDatasetLayout",
    "CuratedPartition",
    "FetchManifest",
    "GameBuildRecord",
    "GameCatalog",
    "GameFetchRecord",
    "NbaScheduleClient",
    "NbaScheduleError",
    "RawArtifactEvidence",
    "ScheduleResponse",
    "SeasonScheduleCache",
    "append_build_record",
    "append_fetch_records",
    "artifact_evidence",
    "build_ledger_frame",
    "build_ledger_from_frame",
    "catalog_frame",
    "catalog_from_frame",
    "catalog_from_schedule",
    "fetch_manifest_frame",
    "fetch_manifest_from_frame",
    "failed_fetch_record",
    "fetch_game_raw",
    "is_transient_fetch_error",
    "read_build_ledger",
    "read_fetch_manifest",
    "read_game_catalog",
    "replace_catalog_season",
    "select_catalog_games",
    "write_build_ledger",
    "write_fetch_manifest",
    "write_game_catalog",
]
